version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd hello
      - npm install
      - npm install -g serverless
  build:
    commands:
      - sls deploy