service: sqs


provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  
functions:
  sender:
    handler: src/sqs-sender.handler
    memorySize: 128
    events:
      #- http:
      #    path: v1/sender
      #    method: post
      - schedule:
          rate: cron(*/2 * * * ? *)
          enabled: false
  receiver:
    handler: src/sqs-receiver.handler
    memorySize: 128